name: Anforderungsvorlage
about: Verwenden Sie diese Vorlage, um eine Anforderung zu erstellen

title: '[Kurze Beschreibung der Anforderung]'

labels:
  - 'Funktionale Anforderung'
  - 'Qualitätsanforderung'
  - 'Randanforderung'

body: |
  **Zielsystem:** [Hier das betroffene Teil- oder Subsystem einfügen]
  **Priorität:** [Hier hohe, mittlere oder niedrige Priorität auswählen]
  **Systemaktivität:** [Hier wählen, ob das System selbständig handeln, eine Funktion für Benutzer anbieten oder eine Schnittstelle benötigen soll]
  **Allf. Ergänzungen:** [Hier zusätzliche Informationen oder Ergänzungen zur Anforderung hinzufügen]
  **Funktionalität:** [Hier die gewünschte Funktionalität beschreiben]
  **Bedingungen:** [Hier zeitliche und logische Bedingungen beschreiben]

assignees: ''
